apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patchesJson6902:
  - target:
      group: batch
      version: v1beta1
      kind: CronJob
      name: in-stock-notifier
    patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/imagePullSecrets/-
        value:
          name: github-registry-philliphemleb
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/-
        value:
          name: APP_ENV
          value: prod
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/envFrom/-
        value:
          secretRef:
            name: in-stock-notifier-app-secrets